### ISSUE TITLE
Multiple Links

### ISSUE THREAD

**Issue by fusionsquare** [osiemsiedem/laravel-autolink#17]
Hi,
thank you for the great package. I figured out that only the first URL are converted into a clickable link.

I there any workaround to convert multiple links?

`<div><a href="https://github.com/osiemsiedem/laravel-autolink">github.com/osiemsiedem/laravel...</a><br>https://github.com/osiemsiedem/laravel-autolink<br>text<br>https://github.com/osiemsiedem/laravel-autolink<br>text</div>`

AND: How can i add at target="_blank" to the converted URLs?

Thanks!

**Comment by bonzai** [comment]
Thanks! I noticed that there was an issue when the text had multiple URLs. It should be fixed now.

As for the second question - the simplest way is to use a callback:

```php
<?php

use OsiemSiedem\Autolink\Elements\UrlElement;
use OsiemSiedem\Autolink\Facades\Autolink;

$text = '<div>https://github.com/osiemsiedem/laravel-autolink<br>https://github.com/osiemsiedem/laravel-autolink<br>text<br>https://github.com/osiemsiedem/laravel-autolink<br>text</div>';

echo Autolink::convert($text, function ($element) {
    if ($element instanceof UrlElement) {
        $element->getAttributes()->setAttribute('target', '_blank');
    }

    return $element;
});
```

You can also make a filter, so you don't need to specify a callback every single time.

1. Publish a config:

```bash
php artisan vendor:publish --provider="OsiemSiedem\Autolink\AutolinkServiceProvider" --tag=config
```

2. Create a file named `TargetBlankFilter.php` in `app/Autolink`:

```php
<?php

namespace App\Autolink;

use OsiemSiedem\Autolink\Contracts\Element;
use OsiemSiedem\Autolink\Contracts\Filter;
use OsiemSiedem\Autolink\Elements\UrlElement;

class TargetBlankFilter implements Filter
{
    public function filter(Element $element): Element
    {
        if ($element instanceof UrlElement) {
            $element->getAttributes()->setAttribute('target', '_blank');
        }

        return $element;
    }
}
```

3. Append your filter in `config/autolink.php`:

```php
'filters' => [
    \OsiemSiedem\Autolink\Filters\TrimFilter::class,
    \OsiemSiedem\Autolink\Filters\LimitLengthFilter::class,
    \App\Autolink\TargetBlankFilter::class,
],
```
