### ISSUE TITLE
Class osiemsiedem.autolink does not exist

### ISSUE THREAD

**Issue by indapublic** [osiemsiedem/laravel-autolink#3]
Hi. I receiving ReflectionException after trying to execute Autolink::convert.

```
laravel/framework                     v5.6.39            The Laravel Framework.
osiemsiedem/laravel-autolink          2.0.2              A Laravel package for converting URLs in a given string of text into clickable links.
```

```
use OsiemSiedem\Autolink\Facades\Autolink;

Autolink::convert('ok')
```

> ReflectionException (-1)
> Class osiemsiedem.autolink does not exist

Tried to clear cache. Nothing helps.

Perhaps I missed something?

Thanks

**Comment by bonzai** [comment]
It works fine for me:

```sh
$ composer create-project laravel/laravel:5.6.33 test
$ cd test
$ composer require osiemsiedem/laravel-autolink:2.0.2
$ php artisan tinker
```
```
>>> use OsiemSiedem\Autolink\Facades\Autolink
>>> (string) Autolink::convert('ok')
=> "ok"
```

Maybe try to run the following commands:

```
$ php artisan clear-compiled
$ composer dump-autoload
```

**Comment by indapublic** [comment]
@bonzai Thanks for reply. Will try in Monday

**Comment by indapublic** [comment]
It works after adding `AutolinkServiceProvider` to `config/app.php` as providers. Perhaps it should be added to readme.

Perhaps it's related to my environment, because 5.6 should auto discover it.

Thanks!
